#!/usr/bin/env python3
"""Render Markdown views per PRODUCT from the module/board model (via model.py).

For each product P, writes into generated/<P>/:
  <conn>.md                — by-pin allocation table per connector that has pins
  sound_connector_cable.md — 20-pin DF40 sound connector (from `dest: Sound pN`)
  by_destination.md        — pins grouped by connector/circuit they feed
  by_tag.md                — pins grouped by tag
  connectors.md            — the connector registry
Do not hand-edit generated/ — edit the module/board/product YAML and re-run (`make render`).
"""
import pathlib
import re

import model

HERE = pathlib.Path(__file__).parent
GEN = HERE / "generated"
BANNER = "<!-- GENERATED by render.py from the module/board model — do not hand-edit. -->\n"


def num(pin):
    return int(pin.split(".")[1])


def rows(pins, conn):
    return sorted((p for p in pins if p.startswith(conn + ".")), key=num)


def alts(d):
    return ", ".join(d.get("alts", [])) or ""


def render_header(pins, conn, cmeta, path):
    title = cmeta.get("desc", conn)
    lines = [BANNER, f"## {conn} — {title} (by pin)\n"]
    if cmeta.get("note"):
        lines.append(f"⚠ {cmeta['note']}\n")
    lines += ["| Pin | SoM | Function | Destination | Alt mux | Verified |",
              "|---|---|---|---|---|---|"]
    for p in rows(pins, conn):
        d = pins[p]
        lines.append(f"| {p} | {d.get('som','—')} | {d['func']} | {d.get('dest','')} "
                     f"| {alts(d)} | {d.get('verified','')} |")
    path.write_text("\n".join(lines) + "\n")
    return len(rows(pins, conn))


def render_sound_cable(pins, path):
    rx = re.compile(r"Sound p(\d+)")
    rowset = []
    for p, d in pins.items():
        m = rx.search(d.get("dest", ""))
        if m:
            rowset.append((int(m.group(1)), d["func"], p, d.get("som", "—")))
    rowset.sort()
    lines = [BANNER, "## Sound connector (20-pin DF40)\n",
             "Generated from `dest: Sound pN`. Power/GND pins (DF40 1/9/10/20) "
             "identify on the board.\n",
             "| DF40 pin | Signal | → Pin | SoM |", "|---|---|---|---|"]
    for n, func, hdr, som in rowset:
        lines.append(f"| {n} | {func} | **{hdr}** | {som} |")
    path.write_text("\n".join(lines) + "\n")
    return len(rowset)


def render_by_dest(pins, path):
    groups = {}
    for p, d in pins.items():
        key = re.sub(r"\s*p\d+.*$", "", d.get("dest", "?")).strip() or "?"
        groups.setdefault(key, []).append(p)
    lines = [BANNER, "## Pins by destination / circuit\n"]
    for key in sorted(groups):
        pset = sorted(groups[key], key=lambda p: (p.split(".")[0], num(p)))
        lines.append(f"- **{key}** ({len(pset)}): {', '.join(pset)}")
    path.write_text("\n".join(lines) + "\n")
    return len(groups)


def render_by_tag(pins, path):
    tags = {}
    for p, d in pins.items():
        for t in d.get("tags", []):
            tags.setdefault(t, []).append(p)
    lines = [BANNER, "## Pins by tag\n"]
    for t in sorted(tags):
        pset = sorted(tags[t], key=lambda p: (p.split(".")[0], num(p)))
        lines.append(f"- **{t}** ({len(pset)}): {', '.join(pset)}")
    path.write_text("\n".join(lines) + "\n")
    return len(tags)


def render_connectors(reg, path):
    order = {"placed": 0, "given": 1, "draft": 2}
    items = sorted(reg.items(),
                   key=lambda kv: (order.get(kv[1].get("status"), 9), kv[0]))
    lines = [BANNER, "## Connector registry\n",
             "`given` = vendor-fixed · `placed` = drawn in KiCad · `draft` = planned.\n",
             "| Connector | Board | Type | Pos | Status | Part | Pinout | How it connects |",
             "|---|---|---|---|---|---|---|---|"]
    for cid, e in items:
        k = e.get("keying")
        key = (f"Key {k}" + ("?" if e.get("keying_status") == "TBD" else "")) if k else ""
        typ = f"{e.get('role','')} {key}".strip()
        doc = e.get("pinout", "")
        doclink = f"[doc]({doc})" if doc else "—"
        lines.append(
            f"| **{e.get('name', cid)}** | {e.get('board','—')} | {typ} "
            f"| {e.get('positions','—')} | {e['status']} | {e.get('part','—')} | {doclink} "
            f"| {e.get('connects', e.get('purpose',''))} |")
    for cid, e in items:
        if e.get("note") or e.get("alternatives"):
            lines.append(f"\n**{e.get('name', cid)}** — {e.get('note','')}"
                         + (f" _Alt:_ {e['alternatives']}"
                            if e.get("alternatives") else ""))
    path.write_text("\n".join(lines) + "\n")
    return len(reg)


def render_product(name):
    M = model.load_product(name)
    pins, connectors = M["pins"], M["connectors"]
    out = GEN / name
    out.mkdir(parents=True, exist_ok=True)
    conns = [c for c in connectors if rows(pins, c)]
    for c in conns:
        render_header(pins, c, connectors[c], out / f"{c}.md")
    ns = render_sound_cable(pins, out / "sound_connector_cable.md")
    nd = render_by_dest(pins, out / "by_destination.md")
    nt = render_by_tag(pins, out / "by_tag.md")
    nc = render_connectors(M["connector_registry"], out / "connectors.md")
    print(f"rendered {name}: connectors {conns} · sound-cable ({ns}) "
          f"destinations ({nd}) tags ({nt}) registry ({nc}) -> {out}/")


def main():
    GEN.mkdir(exist_ok=True)
    for p in model.list_products():
        render_product(p)


if __name__ == "__main__":
    main()
